# ---- Pi-hole FTL --------------------------------------------
[program:pihole]
command=/usr/bin/start.sh
autostart=true
autorestart=true
startretries=5
priority=20
startsecs=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
